version: '3.8'

services:
  diplom:
    image: veiag/diplom:latest
    container_name: diplom
    environment:
      - MYSQL_HOST=mysql # MySQL host (use 172.17.0.1 if using local mysql instance)
      - MYSQL_PORT=3306 # Port of mysql container
      - MYSQL_DATABASE=db # Database name
      - MYSQL_USER=admin # MySQL user
      - MYSQL_PASSWORD=admin # MySQL password
      - AUTH_SECRET=OqW/n3/i/e65kOxpc6juz73UsqidP0hh5qOeV/kQptQ # Secret key for JWT authentication

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local