import type { Metadata } from "next";
import "./globals.css";
// import InitializationChecker from "@/components/InitializationChecker";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
// import MenuBar from "@/components/MenuBar";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
    title: "Diplom",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="uk" suppressHydrationWarning>
            <body>
                {/* <script
                    crossOrigin="anonymous"
                    src="//unpkg.com/react-scan/dist/auto.global.js"
                /> */}
                <SessionProvider>

                <ThemeProvider
                    attribute="class"
                    // defaultTheme="system" 
                    enableSystem
                >
                    {children}
                    <Toaster />
                </ThemeProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
