name: release-pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set release tag
        run: echo "RELEASE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: veiag
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_RELEASE_TAG=${{ env.RELEASE_TAG }}
          tags: |
            veiag/nuft_pk:latest
            veiag/nuft_pk:${{ env.RELEASE_TAG }}
